spring:
  datasource:
    url: jdbc:mysql://localhost:3307/clothify_store
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
