spring:
  datasource:
    url: jdbc:postgresql://ep-lucky-band-a1wgjt8s.ap-southeast-1.aws.neon.tech/clothify_store
    username: clothify_store_owner
    password: t1owbnX8FJGK

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
